server:
  port: 10700
spring:
  application:
    name: eureka.zuul.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HomeInGuanglunshan/temp
          search-paths: spring-cloud-config
    bus:
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9093,localhost:9094,localhost:9095
    consumer:
      group-id: topic-test-cluster
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka-major.com:10100/eureka/,http://admin:123456@eureka-backup1.com:10101/eureka/,http://admin:123456@eureka-backup2.com:10102/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        #include: health, info, refresh
        include: '*'