server:
  port: 11501

spring:
  application:
    name: eureka.zuul.security.second
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  redis:
    host: localhost
    port: 6379
    timeout: 10000
    database: 0
    password:
    lettuce:
      pool:
        max-active: 300
        max-idle: 100
        max-wait: -1
        min-idle: 20
      shutdown-timeout: 10000
  session:
    store-type: redis
    cookieName: custom-cookie #怀疑是作者自定义属性，from: https://blog.csdn.net/zhu124866/article/details/99698986

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka-major.com:10100/eureka/,http://admin:123456@eureka-backup1.com:10101/eureka/,http://admin:123456@eureka-backup2.com:10102/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

ribbon:
  ReadTimeout: 60000
  ConnnectionTimeout: 60000

feign:
  hystrix:
    enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

#阻止启动时提示CONDITION EVALUATION DELTA
spring.devtools.restart.log-condition-evaluation-delta: false

