server:
  port: 11100

spring:
  application:
    name: eureka.zuul.provider
  cloud:
    stream: #from: https://www.cnblogs.com/huangjuncong/p/9102843.html
      kafka:
        binder:
          brokers: localhost:9093,localhost:9094,localhost:9095
          #zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        output:
          destination: stream-demo #In kafka, it's a topic
          #content-type: text/plain
        multiPartOutput:
          destination: multiPartTopic
          producer:
            partitionKeyExpression: payload
            partitionCount: 2
        unprocessed:
          destination: unprocessed

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka-major.com:10100/eureka/,http://admin:123456@eureka-backup1.com:10101/eureka/,http://admin:123456@eureka-backup2.com:10102/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

ribbon:
  ReadTimeout: 60000
  ConnnectionTimeout: 60000

feign:
  hystrix:
    enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

#阻止启动时提示CONDITION EVALUATION DELTA
spring.devtools.restart.log-condition-evaluation-delta: false

