server:
  port: 10201
spring:
  application:
    name: eureka.zuul.gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      #defaultZone: http://admin:123456@127.0.0.1:10100/eureka/
      defaultZone: http://admin:123456@eureka-major.com:10100/eureka/,http://admin:123456@eureka-backup1.com:10101/eureka/,http://admin:123456@eureka-backup2.com:10102/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
zuul:
  routes:
    eureka.zuul.boy:
      path: /eureka.zuul.boy/**
    eureka.zuul.girl:
      path: /eureka.zuul.girl/**
    eureka.zuul.uncle:
      path: /eureka.zuul.uncle/**
    eureka.zuul.aunt:
      path: /eureka.zuul.aunt/**
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

ribbon:
  ReadTimeout: 60000
  ConnnectionTimeout: 60000

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
