server:
  port: 10500

spring:
  application:
    name: eureka.zuul.uncle
  sleuth:
    sampler:
      # 采样率，默认值为0.1f，现在为了测试设置100%采集
      #percentage: 1
      # 2.0后percentage改为probability
      probability: 1
  zipkin:
    #base-url: http://localhost:11000/
    base-url: http://eureka.zuul.zipkin/ #不开zuul网关也没问题

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka-major.com:10100/eureka/,http://admin:123456@eureka-backup1.com:10101/eureka/,http://admin:123456@eureka-backup2.com:10102/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

ribbon:
  ReadTimeout: 60000
  ConnnectionTimeout: 60000
  #解决“Ribbon整合Eureka，出现 No instances available for XXX 异常”
  #否则，请求地址不能为localhost、127.0.0.1、api.weibo.com这些，只能为spring.application.name————两种情形，二选一
  #https://www.cnblogs.com/XingXiaoMeng/p/10958644.html
#  okhttp:
#    enabled: true
#  restclient:
#    enabled: true

#eureka.zuul.girl:  #提供者服务ID
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #负载均衡规则-随机

feign:
  hystrix:
    enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
