server:
  port: 11000

spring:
  application:
    name: eureka.zuul.zipkin
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/index-test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    initialSize: 3 
    minIdle: 2
    maxActive: 60
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    removeAbandoned: true
    removeAbandonedTimeout: 120
    logAbandoned: false
    filters: stat
    # database connection pool setting
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    # Switch this on to create the schema on startup:
    # 弄不好会清空表中已有数据，结果取决于指定的SQL文件内容
    # initialize: true
    # continueOnError: true
    # initialization-mode: always #from: https://blog.csdn.net/alicewang99/article/details/85317093
    # schema: classpath:zipkin-2.9.4.sql
  jpa:
    # Specify the DBMS
    database: MYSQL
    # Show or not log for each sql query
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    hibernate.ddl-auto: update
    # Naming strategy
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    # stripped before adding them to the entity manager
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  zipkin:
    enabled: false
  sleuth:
    enabled: false

zipkin:
  storage:
    type: mysql
#   mysql:
#     jdbc-url: jdbc:mysql://127.0.0.1:3306/index-test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#     host: ${MYSQL_HOST:localhost}
#     port: ${MYSQL_TCP_PORT:3306}
#     username: ${MYSQL_USER:}
#     password: ${MYSQL_PASS:}
#     db: ${MYSQL_DB:index-test}
#     max-active: ${MYSQL_MAX_CONNECTIONS:10}
#     use-ssl: ${MYSQL_USE_SSL:false}

management:
  metrics:
    web:
      server:
        #避免访问zipkin页面报java.lang.IllegalArgumentException
        #from: https://blog.csdn.net/z28126308/article/details/84674254
        auto-time-requests: false

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka-major.com:10100/eureka/,http://admin:123456@eureka-backup1.com:10101/eureka/,http://admin:123456@eureka-backup2.com:10102/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
