server:
  port: 10100
spring:
  application.name: eureka.zuul.registry
  security:
    user:
      name: admin
      password: 123456
eureka:
  instance:
    #instance-id: eureka-major
    #当各个注册中心位于同一机子上时，不能使用localhost，要使用域名，hosts的DNS解析必须配置
    #此时无法登录http://localhost:10100/，只能登录http://eureka-major.com:10100/
    #hostname: eureka-major.com
    preferIpAddress: true
  client:
    #当register-with-eureka为false时，虽然控制台没有报错，但是其他registry皆为unavailable-replicas
    #register-with-eureka: true
    register-with-eureka: false
    #registry-fetch-interval-seconds: 
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/
      #defaultZone: http://admin:123456@127.0.0.1:${server.port}/eureka/
      #defaultZone: http://admin:123456@eureka-backup1.com:10101/eureka/,http://admin:123456@eureka-backup2.com:10102/eureka/
  server:
    #enable-self-preservation: false
    eviction-interval-timer-in-ms: 15000
    